// <auto-generated />
namespace BirimBilgiSistemi.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BBS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BBS));
        
        string IMigrationMetadata.Id
        {
            get { return "202010201056443_BBS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
